package io.github.ygojson.model.data;

import java.util.UUID;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;
import lombok.experimental.SuperBuilder;

/**
 * Model describing the properties of a Print (atomic).
 */
@JsonClassDescription(
	"""
		Describes the information for a print.

		This model contains the properties of the printed card that will not be common to all of them."""
)
@JsonPropertyOrder(
	{
		Print.ID_PROPERTY,
		Print.CARD_ID_PROPERTY,
		Print.SET_ID_PROPERTY,
		Print.SET_PREFIX_PROPERTY,
		Print.PRINT_NUMBER_PROPERTY,
		Print.RARITY_PROPERTY,
		Print.LANGUAGE_PROPERTY,
	}
)
@Getter
@SuperBuilder(toBuilder = true)
@JsonPOJOBuilder
public class Print {

	public static final String ID_PROPERTY = "id";
	public static final String CARD_ID_PROPERTY = "cardId";
	public static final String SET_ID_PROPERTY = "setId";
	public static final String SET_PREFIX_PROPERTY = "setPrefix";
	public static final String PRINT_NUMBER_PROPERTY = "printNumber";
	public static final String RARITY_PROPERTY = "rarity";
	public static final String LANGUAGE_PROPERTY = "language";

	/**
	 * UUID (v5) for the Print (atomic) generated by YGOJSON.
	 */
	@JsonPropertyDescription(
		"UID (v5) for the Print (atomic) generated by YGOJSON."
	)
	@NotNull @JsonProperty(value = ID_PROPERTY, required = true)
	@JsonInclude(JsonInclude.Include.ALWAYS)
	private UUID id;

	/**
	 * UUID (v5) generated by YGOJSON of the card that is associated to this print.
	 * </br>
	 * This associates the print with the {@link Card}.
	 *
	 * @see Card#getId()
	 */
	@JsonPropertyDescription(
		"UID (v5) for the Card (atomic) associated with this print (generated by YGOJSON)."
	)
	@NotNull @JsonProperty(value = CARD_ID_PROPERTY)
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	private UUID cardId;

	/**
	 * UUID (v5) generated by YGOJSON of the set that is associated to this print.
	 * </br>
	 * This associates the print with the {@link Set}.
	 *
	 * @see Set#getId()
	 */
	@JsonPropertyDescription(
		"UID (v5) for the Set (atomic) associated with this print (generated by YGOJSON)."
	)
	@NotNull @JsonProperty(value = SET_ID_PROPERTY)
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	private UUID setId;

	/**
	 * Set prefix associated with this print.
	 * </br>
	 * Together with the {@link #getPrintNumber()} generates the full print-code.
	 * </br>
	 * This property might differ from the {@link Set#getPrefix()} associated for this
	 * print, as prints-codes are often localized.
	 */
	@JsonPropertyDescription(
		"""
			Set prefix associated with this print.

			This property might differ with the prefix on the Set Model as the print-codes are often localized."""
	)
	@JsonProperty(value = SET_PREFIX_PROPERTY)
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	@Pattern(regexp = "[a-zA-Z0-9]+-[a-zA-Z0-9]+")
	private String setPrefix;

	/**
	 * Number of the print within the set.
	 * </br>
	 * Together with the {@link #getSetPrefix()} generates the full printCode.
	 * </br>
	 * Although this property is usually a numeric with left-padded zeroes,
	 * there are few cases where a letter is at the end (i.e., "K-Series").
	 */
	@JsonPropertyDescription(
		"""
			Number of the print within the set.

			It is represented as a string with left-padded zeroes, although sometimes might contain a letter."""
	)
	@JsonProperty(value = PRINT_NUMBER_PROPERTY)
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	@Pattern(regexp = "[a-zA-Z0-9]+")
	private String printNumber;

	/**
	 * Rarity of the print.
	 * </br>
	 * The rarity of the card print.
	 */
	@JsonPropertyDescription("Rarity of the print")
	@JsonProperty(value = RARITY_PROPERTY)
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	private String rarity;

	/**
	 * Language of the print.
	 * </br>
	 * The language of the card print.
	 */
	@JsonPropertyDescription("Language of the print")
	@JsonProperty(value = LANGUAGE_PROPERTY)
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	private String language;
}
