# overriden DEV quarkus config
quarkus:
  datasource:
    jdbc:
      url: "jdbc:sqlite:file:.tmp/dev.db?mode=rwc"
  log:
    level: "INFO"
    console:
      stderr: true
    category:
      "org.hibernate.SQL":
        level: "DEBUG"
      "io.github.ygojson":
        level: "DEBUG"
