# ygojson-specific properties
ygojson:
  url: "https://github.com/ygojson/ygojson-tools"

# quarkus config
quarkus:
  hibernate-orm:
    database:
      generation: "drop-and-create"
  datasource:
    db-kind: "sqlite"
    jdbc:
      url: "jdbc:sqlite::memory:"
  log:
    level: "WARN"
    console:
      stderr: true
      format: "[%-5p - %d{yyyy-MM-dd HH:mm:ss}] - %s%n"
    category:
      "io.github.ygojson":
        level: "INFO"
  banner:
    enabled: false
    path: banner.txt
