# overriden DEV quarkus config
quarkus:
  datasource:
    jdbc:
      url: "jdbc:sqlite:file:.tmp/dev.db?mode=rwc"
  rest-client:
    logging:
      scope: "request-response"
      body-limit: 1000
  log:
    level: "INFO"
    console:
      stderr: true
    category:
      "org.jboss.resteasy.reactive.client.logging":
        level: "DEBUG"
      "org.hibernate.SQL":
        level: "DEBUG"
      "io.github.ygojson":
        level: "DEBUG"
