# overriden DEV quarkus config
quarkus:
  log:
    level: "INFO"
    console:
      stderr: true
    category:
      "org.hibernate.SQL":
        level: "DEBUG"
      "io.github.ygojson":
        level: "DEBUG"
