# overriden TEST quarkus config
quarkus:
  datasource:
    jdbc:
      url: "jdbc:sqlite:file:.tmp/test.db?mode=rwc"
  log:
    console:
      stderr: true
    category:
      "org.hibernate.SQL":
        level: "DEBUG"
      "io.github.ygojson":
        level: "DEBUG"
