# ygojson-specific properties
ygojson:
  url: "https://github.com/ygojson/ygojson-tools"

# quarkus config
quarkus:
  flyway:
    migrate-at-start: true
  hibernate-orm:
    database:
      generation: "validate"
  datasource:
    db-kind: "sqlite"
    jdbc:
      url: "jdbc:sqlite::memory:"
  log:
    level: "WARN"
    console:
      stderr: true
    category:
      "io.github.ygojson":
        level: "INFO"
  banner:
    enabled: false
    path: banner.txt
