# ygojson-specific properties
ygojson:
  url: "https://github.com/ygojson/ygojson-tools"

# quarkus config
quarkus:
  log:
    level: "WARN"
    console:
      stderr: true
      format: "[%-5p - %d{yyyy-MM-dd HH:mm:ss}] - %s%n"
    category:
      "io.github.ygojson":
        level: "INFO"
  banner:
    path: banner.txt
