# ygojson-specific properties
ygojson:
  url: "https://github.com/ygojson/ygojson-tools"

# quarkus config
quarkus:
  # database
  flyway:
    migrate-at-start: true
  hibernate-orm:
    database:
      generation: "validate"
  datasource:
    db-kind: "sqlite"
    jdbc:
      url: "jdbc:sqlite::memory:"
  # logging
  log:
    level: "WARN"
    console:
      stderr: true
    category:
      "io.github.ygojson":
        level: "INFO"
  # default JSON (not final model json)
  jackson:
    fail-on-unknown-properties: false
    fail-on-empty-beans: false
    serialization-inclusion: NON_ABSENT
    write-dates-as-timestamps: false
  # banner
  banner:
    enabled: false
    path: banner.txt
