package io.github.ygojson.tools.dataprovider.impl.yugipedia.model.wikitext;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.github.ygojson.tools.dataprovider.impl.yugipedia.model.IntegerOrUndefined;

/**
 * Yugipedia's Model for CardTable2.
 * <br>
 * {@link MarkupString} is used where markup content might be present.
 * The rest of fields are typed as {@link String} to prevent issues
 * while typing values with special markers (i.e., atk/def values as '?'
 * cannot be typed as a numeric).
 *
 * @see <a href=https://yugipedia.com/wiki/Template:CardTable2>CardTable2</a>
 */
public record CardTable2(
	String cardclass,
	String name,
	String fr_name,
	String de_name,
	String it_name,
	String it_trans_name,
	String pt_name,
	String es_name,
	MarkupString ja_name,
	String romaji_name,
	String trans_name,
	String base_romaji_name,
	String base_trans_name,
	String zh_name,
	String zh_pinyin_name,
	String zh_trans_name,
	String sc_name,
	String sc_pinyin_name,
	String tc_name,
	MarkupString ko_name,
	String ko_rr_name,
	String ko_trans_name,
	String alt_name,
	String alt_name2,
	String alt_name3,
	String ja_alt_name,
	String ja_alt_romaji,
	String ja_alt_trans,
	String image,
	String image2,
	String current_image,
	String card_type,
	String property,
	String attribute,
	String character,
	String types,
	String level,
	String rank,
	List<String> link_arrows,
	String pendulum_scale,
	String maximum_atk,
	IntegerOrUndefined atk,
	IntegerOrUndefined def,
	String password,
	String limitation_text,
	String ritualcard,
	String ritualmonster,
	String summon,
	String effect_types,
	String pendulum_effect_types,
	String ocg_status,
	String tcg_status,
	String tcg_speed_duel_status,
	String source_card,
	String skill_activation,
	String fr_skill_activation,
	String de_skill_activation,
	String it_skill_activation,
	String pt_skill_activation,
	String es_skill_activation,
	MarkupString pendulum_effect,
	MarkupString fr_pendulum_effect,
	MarkupString de_pendulum_effect,
	MarkupString it_pendulum_effect,
	MarkupString pt_pendulum_effect,
	MarkupString es_pendulum_effect,
	MarkupString ja_pendulum_effect,
	MarkupString trans_pendulum_effect,
	MarkupString zh_pendulum_effect,
	MarkupString sc_pendulum_effect,
	MarkupString tc_pendulum_effect,

	MarkupString ko_pendulum_effect,
	MarkupString lore,
	MarkupString fr_lore,
	MarkupString de_lore,
	MarkupString it_lore,
	MarkupString pt_lore,
	MarkupString es_lore,
	MarkupString ja_lore,
	MarkupString trans_lore,
	MarkupString zh_lore,
	MarkupString sc_lore,
	MarkupString tc_lore,
	MarkupString ko_lore,
	String use,
	String database_id,
	List<MarkupString> en_sets,
	List<MarkupString> na_sets,
	List<MarkupString> eu_sets,
	List<MarkupString> au_sets,
	List<MarkupString> fr_sets,
	List<MarkupString> fc_sets,
	List<MarkupString> de_sets,
	List<MarkupString> it_sets,
	List<MarkupString> pt_sets,
	List<MarkupString> sp_sets,
	List<MarkupString> jp_sets,
	List<MarkupString> ja_sets,
	List<MarkupString> ae_sets,
	List<MarkupString> tc_sets,
	List<MarkupString> sc_sets,
	List<MarkupString> kr_sets,
	MarkupString supports,
	String mentions,
	@JsonProperty("anti-supports") // not valid java variable name
	String anti_supports,
	String archseries,
	String related_to_archseries,
	String supports_archetypes,
	@JsonProperty("anti-supports_archetypes") // not valid java variable name
	String anti_supports_archetypes,
	String related_to_archetypes,
	String counter,
	String action,
	String stat_change,
	@JsonProperty("m/s/t") // not valid java variable name
	String m_s_t,
	String summoning,
	String attack,
	String banished,
	String life_points,
	String fm_for,
	String sm_for,
	String misc,
	String material,
	String materials,
	String fusion_material,
	String synchro_material,
	String ntr_sets,
	String ygo_lore,
	String ygo_sets,
	String gx1_dp,
	String gx1_lore,
	String gx1_number,
	String gx1_sets,
	String gx03_sets,
	String gx03_status
) {}
