CREATE TABLE
    IF NOT EXISTS "tbl_card" (
        "card_id" VARCHAR(36) UNIQUE NOT NULL,
        "ygojson_id" VARCHAR(36) UNIQUE,
        "konami_id" BIGINT UNIQUE,
        "password" BIGINT UNIQUE,
        "password_alt" BIGINT UNIQUE,
        "yugipedia_pageid" BIGINT UNIQUE,
        "card_type" VARCHAR(255),
        "property" VARCHAR(255),
        "monster_types" VARCHAR(255),
        "attribute" VARCHAR(255),
        "atk" INTEGER,
        "atk_undef" BOOLEAN,
        "def" INTEGER,
        "def_undef" BOOLEAN,
        "level" INTEGER,
        "pendulum_scale" INTEGER,
        "link_rating" INTEGER,
        "link_arrows" VARCHAR(255),
        "xyz_rank" INTEGER,
        "name" VARCHAR(255),
        "effect_text" VARCHAR(255),
        "flavor_text" VARCHAR(255),
        "materials_text" VARCHAR(255),
        "pendulum_effect_text" VARCHAR(255),
        "de_name" VARCHAR(255),
        "de_effect_text" VARCHAR(255),
        "de_flavor_text" VARCHAR(255),
        "de_materials_text" VARCHAR(255),
        "de_pendulum_effect_text" VARCHAR(255),
        "es_name" VARCHAR(255),
        "es_effect_text" VARCHAR(255),
        "es_flavor_text" VARCHAR(255),
        "es_materials_text" VARCHAR(255),
        "es_pendulum_effect_text" VARCHAR(255),
        "fr_name" VARCHAR(255),
        "fr_effect_text" VARCHAR(255),
        "fr_flavor_text" VARCHAR(255),
        "fr_materials_text" VARCHAR(255),
        "fr_pendulum_effect_text" VARCHAR(255),
        "it_name" VARCHAR(255),
        "it_effect_text" VARCHAR(255),
        "it_flavor_text" VARCHAR(255),
        "it_materials_text" VARCHAR(255),
        "it_pendulum_effect_text" VARCHAR(255),
        "ja_name" VARCHAR(255),
        "ja_effect_text" VARCHAR(255),
        "ja_flavor_text" VARCHAR(255),
        "ja_materials_text" VARCHAR(255),
        "ja_pendulum_effect_text" VARCHAR(255),
        "ko_name" VARCHAR(255),
        "ko_effect_text" VARCHAR(255),
        "ko_flavor_text" VARCHAR(255),
        "ko_materials_text" VARCHAR(255),
        "ko_pendulum_effect_text" VARCHAR(255),
        "pt_name" VARCHAR(255),
        "pt_effect_text" VARCHAR(255),
        "pt_flavor_text" VARCHAR(255),
        "pt_materials_text" VARCHAR(255),
        "pt_pendulum_effect_text" VARCHAR(255),
        "zhhans_name" VARCHAR(255),
        "zhhans_effect_text" VARCHAR(255),
        "zhhans_flavor_text" VARCHAR(255),
        "zhhans_materials_text" VARCHAR(255),
        "zhhans_pendulum_effect_text" VARCHAR(255),
        "zhhant_name" VARCHAR(255),
        "zhhant_effect_text" VARCHAR(255),
        "zhhant_flavor_text" VARCHAR(255),
        "zhhant_materials_text" VARCHAR(255),
        "zhhant_pendulum_effect_text" VARCHAR(255),
        primary key (card_id)
    );

CREATE UNIQUE INDEX "index.tbl_card.id" ON "tbl_card" ("card_id");

CREATE UNIQUE INDEX "index.tbl_card.ygojson_id" ON "tbl_card" ("ygojson_id");

CREATE UNIQUE INDEX "index.tbl_card.setcode" ON "tbl_card" ("konami_id");

CREATE UNIQUE INDEX "index.tbl_card.password" ON "tbl_card" ("password");

CREATE UNIQUE INDEX "index.tbl_card.yugipedia_pageid" ON "tbl_card" ("yugipedia_pageid");

CREATE INDEX "index.tbl_card.name" ON "tbl_card" ("name");